### PR TITLE
Add Replicate demo and API

### PR DESCRIPTION
**Pull request by chenxwh**
Hey @Xiangtaokong  ! 👋 

This pull request makes it possible to run your model inside a Docker environment, which makes it easier for other people to run it.  We're using an open source tool called [Cog](https://github.com/replicate/cog) to make this process easier.

This also means we can make a web page where other people can run your model! We have added `HAT_SRx4_ImageNet` for `SingleImageDataset` for people to easily test their own input image, view it here: https://replicate.com/cjwbw/hat

Replicate also have an API, so people can easily run your model from their code:

```python
import replicate
model = replicate.models.get("cjwbw/hat")
output = model.predict(image="...")
```

You are more than welcome to modify the Replicate page (e.g. [Example](https://replicate.com/cjwbw/hat/examples) Gallery), let me know and I can transfer ownership to your account.

In case you're wondering who I am, I'm from [Replicate](https://replicate.com/home), where we're trying to make machine learning reproducible. We got frustrated that we couldn't run all the really interesting ML work being done. So, we're going round implementing models we like. 😊

### CODE REVIEW

**Comment by chxy95** [comment]
@chenxwh Thanks for your great work to make the demo! My ID is @chxy95.

**Comment by chenxwh** [comment]
Thanks for the merge! Have now transferred to your orgs replicate page here: https://replicate.com/xpixelgroup/hat

**Comment by chxy95** [comment]
Hi @chenxwh, thanks for your work again! Due to the limited memory of the utilized GPU, some users reported that the error of 'out of CUDA memory' would be occurred for high-resolution inputs, eg. 512 x 512. I would like to ask if it is possible to deploy this project on a GPU with more memory?

**Comment by chenxwh** [comment]
Hi @chxy95,

Sure, the model will be now host on A100 (which also means that people need to sign in to replicate to run it).

**Comment by chxy95** [comment]
Hi @chenxwh, an error occurs when running the model on the replicate page: ''RuntimeError: CUDA error: no kernel image is available for execution on the device''. It seems that there are some problems with the environment currently used.

**Comment by chenxwh** [comment]
ah yes, on A100 the torch needs to installed differently. I have updated cog.yaml as in [here](https://github.com/chenxwh/HAT/blob/main/cog.yaml), and pushed a new version to the web page.

Now that the model page is under your orgs name, with [Cog](https://github.com/replicate/cog) installed then on terminal 
`cog login`
`cog push r8.im/xpixelgroup/hat` 
you can update the demo page however you like. The PR serves more of a showcase for how models can be hosted on Replicate, we encourage you to give it a go or deploy other models on Replicate too :)

**Comment by chxy95** [comment]
Okay, I understand. Thanks for your support again!

**Comment by chxy95** [comment]
@kadirnar Try the Real-HAT model in this repo. The Replicate demo only supports Bicubic downsampling kernel currently.

**Comment by chxy95** [comment]
Hi @chenxwh, I'm currently trying to upload our updated model to Replicate. Tried `sudo cog login` and `sudo cog push .... ` to no avail. Strangely, I was told that I am not logged in.
Below is full stack trace:
```
sudo cog push r8.im/chxy95/hat_test
/etc/host.conf: line 5: bad command `34.194.164.123 registry-1.docker.io'
⚠ Cog doesn't know if CUDA 11.7 is compatible with PyTorch 1.9.1. This might cause CUDA problems.
Building Docker image from environment in cog.yaml as r8.im/chxy95/hat_test...
[+] Building 23.6s (20/20) FINISHED                                                                                        docker:default
 => [internal] load .dockerignore                                                                                                    0.0s
 => => transferring context: 2B                                                                                                      0.0s
 => [internal] load build definition from Dockerfile                                                                                 0.0s
 => => transferring dockerfile: 2.07kB                                                                                               0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4                                                                        10.8s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc    0.0s
 => [internal] load metadata for docker.io/nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04                                              10.8s
 => [stage-0  1/12] FROM docker.io/nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04@sha256:614af051f58c25ab32d7bb2cfd826108c7aded74fc1cd  0.0s
 => [internal] load build context                                                                                                    0.0s
 => => transferring context: 126.90kB                                                                                                0.0s
 => CACHED [stage-0  2/12] RUN --mount=type=cache,target=/var/cache/apt set -eux; apt-get update -qq; apt-get install -qqy --no-ins  0.0s
 => CACHED [stage-0  3/12] RUN --mount=type=cache,target=/var/cache/apt apt-get update -qq && apt-get install -qqy --no-install-rec  0.0s
 => CACHED [stage-0  4/12] RUN curl -s -S -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | b  0.0s
 => CACHED [stage-0  5/12] COPY .cog/tmp/build885872824/cog-0.0.1.dev-py3-none-any.whl /tmp/cog-0.0.1.dev-py3-none-any.whl           0.0s
 => CACHED [stage-0  6/12] RUN --mount=type=cache,target=/root/.cache/pip pip install /tmp/cog-0.0.1.dev-py3-none-any.whl            0.0s
 => CACHED [stage-0  7/12] RUN --mount=type=cache,target=/var/cache/apt apt-get update -qq && apt-get install -qqy libgl1-mesa-glx   0.0s
 => CACHED [stage-0  8/12] COPY .cog/tmp/build885872824/requirements.txt /tmp/requirements.txt                                       0.0s
 => CACHED [stage-0  9/12] RUN --mount=type=cache,target=/root/.cache/pip pip install -r /tmp/requirements.txt                       0.0s
 => CACHED [stage-0 10/12] RUN pip install basicsr==1.3.4.9                                                                          0.0s
 => CACHED [stage-0 11/12] WORKDIR /src                                                                                              0.0s
 => [stage-0 12/12] COPY . /src                                                                                                      0.5s
 => preparing layers for inline cache                                                                                                1.4s
 => exporting to image                                                                                                               0.0s
 => => exporting layers                                                                                                              0.0s
 => => writing image sha256:2169c503258b96d0dc330a10221ad4a2b6f676b7793362636e2562a232444b3f                                         0.0s
 => => naming to r8.im/chxy95/hat_test                                                                                               0.0s
Validating model schema...
Adding labels to image...
Unable to determine Git tag

Pushing image 'r8.im/chxy95/hat_test'...
Using default tag: latest
The push refers to repository [r8.im/chxy95/hat_test]
1fb61b2e7884: Waiting 
1bcfd05ec69b: Waiting 
9cb953e40815: Waiting 
f7c855421900: Waiting 
1da8f0dc75bc: Waiting 
2cb75f81f27a: Waiting 
2931848837d5: Waiting 
12ec09233c37: Waiting 
d85f74b80237: Waiting 
cbca0751b2af: Waiting 
bbf82b676c3b: Waiting 
9749408344b0: Waiting 
c849e7c2ffe2: Waiting 
b80128169a41: Waiting 
64e498fb2b07: Waiting 
83bb8080cf18: Waiting 
d8896e9cac96: Waiting 
d7ba0e539ec5: Waiting 
b7fcbe119cb4: Waiting 
428ccdee2939: Waiting 
adc7204541f3: Waiting 
dbd551750591: Waiting 
cdd7c7392317: Waiting 
unauthorized: You are not logged in to Replicate. Run 'cog login' and try again.
ⅹ exit status 1
```
I wonder if there is any solution for this error, looking forward to your advice!

**Pull request merged**
